'use client'

import AudioPlayer from './components/AudioPlayer'
import './globals.css'

import { Inter, Poppins, Lato } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({ subsets: ['latin'], weight: '400' })
const lato = Lato({ subsets: ['latin'], weight: '400' })

// export const metadata = {
//     title: 'AI Quiz Generator',
//     description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${poppins.className} relative`}>
                <div className='bg-grid'>
                    <div className='gradient' />
                </div>

                <div className='fixed top-0 right-0 m-1 z-20'>
                    <AudioPlayer />
                </div>

                <main className='relative z-10 max-w-7xl mx-auto sm:px-16 px-6'>
                    {children}
                </main>
            </body>
        </html>
    )
}
