export const facts = [
    'The first website ever created is still online and can be visited at its original URL: info.cern.ch/hypertext/WWW/TheProject.html',
    'The average lifespan of a web page is only about 100 days.',
    "The world's largest website is Facebook, with over 2.85 billion monthly active users.",
    "The term 'weblog' was first coined by Jorn Barger in 1997, and later shortened to 'blog'.",
    'JavaScript was originally created in just 10 days by Brendan Eich in May 1995.',
    "The first web browser was created by Sir Tim Berners-Lee and was called 'WorldWideWeb'.",
    'The most popular programming language for web development is currently JavaScript.',
    "The '404' error message originated from a room number at CERN, where the World Wide Web was invented.",
    'The first webcam was invented to monitor a coffee pot at Cambridge University in 1991.',
    'The first banner ad on the web was used by AT&T in 1994 and had a click-through rate of 44%.',
    'The first website to use a CSS stylesheet was created in 1996.',
    'The first version of HTML was based on SGML, a markup language for creating structured documents.',
    'The first mobile website was created in 1996 for a group of Finnish mobile phone users.',
    'The first browser to support HTML5 was Google Chrome in 2009.',
    'The first website to use a responsive design was Audi.com in 2001.',
    'The first website to use a JavaScript framework was Gmail, which used AngularJS in 2010.',
    'The most popular content management system (CMS) for websites is currently WordPress, which powers over 40% of all websites on the internet.',
    'The first website to use a database to store and retrieve information was created in 1993.',
    'The first website to use a search engine was created in 1993 and was called Aliweb.',
    "The first e-commerce transaction was made on August 11, 1994, when a man sold a CD of Sting's Ten Summoner's Tales to a friend through his website, NetMarket.",
	"Python was named after the British comedy group Monty Python, not the snake.",
    "The Zen of Python is a collection of guiding principles for writing computer programs in Python. It is included as an Easter egg in the Python interpreter and can be accessed by typing 'import this'.",
    "Guido van Rossum created Python in the late 1980s while working at the National Research Institute for Mathematics and Computer Science in the Netherlands.",
    "Python is one of the official programming languages used at Google.",
    "The popular game Minecraft's Pi edition is programmed in Python.",
    "NASA has used Python for scientific programming tasks, including analyzing data from the Mars rovers.",
    "Python has been used to create popular websites such as Instagram, YouTube, and Reddit.",
    "Python is the fastest-growing programming language and has been ranked the most popular language in numerous surveys.",
    "The first version of Python was released on February 20, 1991.",
    "Python's popularity has inspired the creation of numerous Python-themed conferences, such as PyCon and PyData."
]
