export const topics = {
    python: [
        'Random',
        'Data Types',
        'Variables',
        'Basic Syntax',
        'Control Structures',
        'Functions',
        'Lists',
        'Dictionaries',
        'Tuples',
        'Input/Output',
        'Modules',
        'OOP',
        'File I/O',
        'Regular expressions',
        'Decorators',
        'Generators',
        'Multithreading',
        'Networking',
        'Data structures',
        'Error handling',
        'Debugging',
    ],
    javascript: [
        'Random',
        'Variables',
        'Data types',
        'Functions',
        'Conditional statements',
        'Loops',
        'Arrays',
        'Objects',
        'DOM manipulation',
        'Events',
        'Basic syntax',
        'Closures',
        'Scope',
        'Higher-order functions',
        'Promises',
        'Async/Await',
        'ES6+ features',
        'Regular expressions',
        'Error handling',
        'Debugging techniques',
    ],
    react: [
        'Random',
        'JSX',
        'Components',
        'Props',
        'State',
        'Lifecycle Methods',
        'Event Handling',
        'Conditional Rendering',
        'Lists and Keys',
        'Forms',
        'Hooks',
        'Class Components',
        'React Router',
        'React Context',
    ],
    css: [
        'Random',
        'Selectors',
        'Box Model',
        'Layouts',
        'Typography',
        'Colors and Backgrounds',
        'CSS Units',
        'Grid',
        'Flexbox',
        'Display and Visibility',
        'CSS Pseudo-classes',
        'CSS Pseudo-elements',
    ],
}
